openapi: 3.0.3
info:
  title: Outage Aggregator API
  version: 1.0.0
  description: API for ingesting raw controller outages and querying aggregated outage events.
servers:
  - url: http://localhost:3000
paths:
  /ingest:
    post:
      summary: Enqueue a raw outage record for aggregation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestRequest'
      responses:
        '200':
          description: The record was accepted for processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestResponse'
        '400':
          description: Validation error.
  /outages:
    get:
      summary: Query aggregated outage events
      parameters:
        - in: query
          name: type
          required: true
          schema:
            $ref: '#/components/schemas/OutageType'
        - in: query
          name: start
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: end
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: controllerId
          schema:
            type: string
      responses:
        '200':
          description: Aggregated outage events matching the filters.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AggregatedOutage'
        '400':
          description: Validation error.
components:
  schemas:
    OutageType:
      type: string
      enum:
        - panel_outage
        - temperature_outage
        - led_outage
    IngestRequest:
      type: object
      required:
        - controllerId
        - outageType
        - reportedAt
      properties:
        controllerId:
          type: string
          description: Controller identifier following the format AOT1D-YYMM####.
          example: AOT1D-25090001
        outageType:
          $ref: '#/components/schemas/OutageType'
        reportedAt:
          type: string
          format: date-time
          description: Timestamp at which the controller detected the outage.
          example: 2025-01-15T07:43:00Z
    IngestResponse:
      type: object
      properties:
        ok:
          type: boolean
          example: true
        queued:
          type: boolean
          example: true
    AggregatedOutage:
      type: object
      required:
        - id
        - controllerId
        - outageType
        - startTime
        - endTime
      properties:
        id:
          type: integer
          format: int64
        controllerId:
          type: string
        outageType:
          $ref: '#/components/schemas/OutageType'
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
